---
#using of handlers

- name: using of handlers
  hosts: servers
  become: true
  tasks:
    - name: install apache2 
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: restart apache 

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
